import { Link, useNavigate, useOutletContext, useParams } from "react-router-dom";
import { HiOutlineArrowLeft, HiOutlineArrowPath, HiOutlineCheckCircle, HiOutlineClock, HiOutlineMap, HiOutlineMapPin, HiOutlineShoppingBag, HiOutlineXCircle } from "react-icons/hi2";
import { useOrderTracking } from "../hooks/useOrderTracking";
import { useTheme } from "../context/ThemeContext";

const statusCopy = {
  posted: ["Awaiting a receiver", "This donation is still available to claim."],
  reserved: ["Pickup is being coordinated", "The receiver address is confirmed and delivery is pending."],
  completed: ["Rescue delivered", "The food reached its receiver successfully."],
  cancelled: ["Rescue cancelled", "This rescue is closed and no further action is required."],
};

export default function OrderTracking() {
  const ctx = useOutletContext() || {};
  const { dark: appDark } = useTheme();
  const dark = ctx.dark ?? appDark;
  const T = ctx.T || (dark ? { bg: "#080e0a", bgCard: "#111c14", bgAlt: "#0d1710", border: "rgba(34,197,94,.12)", text: "#ecfdf5", textMuted: "#8ab798", textFaint: "#587061", accent: "#32ad63", accentSoft: "rgba(50,173,99,.1)", red: "#ef4444" } : { bg: "#f3f7f4", bgCard: "#fff", bgAlt: "#eaf1ec", border: "rgba(25,76,42,.1)", text: "#132219", textMuted: "#587061", textFaint: "#829087", accent: "#278a50", accentSoft: "rgba(39,138,80,.09)", red: "#dc2626" });
  const { orderId } = useParams();
  const navigate = useNavigate();
  const tracking = useOrderTracking(orderId);

  return <main className="ot-page" style={{ "--ot-bg": T.bg, "--ot-card": T.bgCard, "--ot-soft": T.bgAlt, "--ot-line": T.border, "--ot-text": T.text, "--ot-muted": T.textMuted, "--ot-faint": T.textFaint, "--ot-accent": T.accent, "--ot-accent-soft": T.accentSoft, "--ot-red": T.red }}>
    <style>{`
      .ot-page{min-height:100vh;padding:28px;background:var(--ot-bg);color:var(--ot-text);font-family:var(--font-body)}.ot-shell{width:min(1050px,100%);margin:auto}.ot-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:24px}.ot-kicker{margin-bottom:6px;color:var(--ot-accent);font:500 10px var(--font-meta);letter-spacing:.12em;text-transform:uppercase}.ot-head h1{margin:0;font-size:28px;letter-spacing:-.035em}.ot-head p{margin:7px 0 0;color:var(--ot-muted);font-size:14px}.ot-icon-btn{width:40px;height:40px;display:grid;place-items:center;border:1px solid var(--ot-line);border-radius:10px;background:var(--ot-card);color:var(--ot-muted);cursor:pointer}.ot-alert,.ot-empty{padding:18px;border:1px solid var(--ot-line);border-radius:14px;background:var(--ot-card);color:var(--ot-muted)}.ot-alert{border-color:color-mix(in srgb,var(--ot-red) 25%,transparent);color:var(--ot-red)}
      .ot-list{display:grid;gap:12px}.ot-order{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;padding:18px 20px;border:1px solid var(--ot-line);border-radius:15px;background:var(--ot-card);color:inherit;text-decoration:none;transition:.18s}.ot-order:hover{transform:translateY(-2px);border-color:var(--ot-accent)}.ot-order-top{display:flex;align-items:center;gap:12px}.ot-food-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:11px;background:var(--ot-accent-soft);color:var(--ot-accent)}.ot-food-icon svg{width:20px}.ot-order h2{margin:0;font-size:15px}.ot-meta{display:flex;flex-wrap:wrap;gap:7px;margin-top:5px;color:var(--ot-muted);font-size:11px}.ot-order-side{text-align:right}.ot-status{display:inline-block;padding:5px 9px;border-radius:100px;background:var(--ot-accent-soft);color:var(--ot-accent);font:600 9px var(--font-meta);text-transform:uppercase}.ot-order-side small{display:block;margin-top:8px;color:var(--ot-faint)}
      .ot-detail-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.7fr);gap:16px}.ot-card{padding:20px;border:1px solid var(--ot-line);border-radius:16px;background:var(--ot-card)}.ot-hero{margin-bottom:16px;padding:24px}.ot-hero-row{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.ot-hero h2{margin:0;font-size:22px}.ot-hero p{margin:7px 0 0;color:var(--ot-muted);font-size:13px}.ot-live{display:flex;align-items:center;gap:6px;color:var(--ot-accent);font:600 9px var(--font-meta);letter-spacing:.08em}.ot-live i{width:7px;height:7px;border-radius:50%;background:var(--ot-accent);box-shadow:0 0 0 5px var(--ot-accent-soft)}.ot-progress{height:7px;margin-top:22px;overflow:hidden;border-radius:20px;background:var(--ot-soft)}.ot-progress span{display:block;height:100%;border-radius:inherit;background:var(--ot-accent);transition:width .4s}.ot-progress-copy{display:flex;justify-content:space-between;margin-top:8px;color:var(--ot-muted);font-size:10px}
      .ot-steps{display:grid;gap:0}.ot-step{position:relative;display:grid;grid-template-columns:36px 1fr;gap:12px;padding-bottom:22px}.ot-step:last-child{padding-bottom:0}.ot-step:before{content:'';position:absolute;left:17px;top:34px;bottom:0;width:2px;background:var(--ot-line)}.ot-step:last-child:before{display:none}.ot-step-icon{width:36px;height:36px;display:grid;place-items:center;z-index:1;border:2px solid var(--ot-line);border-radius:50%;background:var(--ot-card);color:var(--ot-faint)}.ot-step.done .ot-step-icon{border-color:var(--ot-accent);background:var(--ot-accent);color:#fff}.ot-step.active .ot-step-icon{border-color:var(--ot-accent);color:var(--ot-accent)}.ot-step h3{margin:2px 0 3px;font-size:13px}.ot-step p{margin:0;color:var(--ot-muted);font-size:11px}.ot-label{margin:0 0 10px;color:var(--ot-faint);font:500 9px var(--font-meta);letter-spacing:.1em;text-transform:uppercase}.ot-address{display:flex;gap:9px;font-size:13px;line-height:1.5}.ot-address svg{width:18px;flex:none;color:var(--ot-accent)}.ot-side{display:grid;align-content:start;gap:14px}.ot-actions{display:grid;gap:8px}.ot-button{width:100%;padding:10px 13px;border:1px solid var(--ot-line);border-radius:9px;background:var(--ot-card);color:var(--ot-text);font:650 12px var(--font-body);text-align:center;text-decoration:none;cursor:pointer}.ot-button.primary{border-color:var(--ot-accent);background:var(--ot-accent);color:#fff}.ot-button.danger{color:var(--ot-red)}.ot-button:disabled{opacity:.55;cursor:wait}
      @media(max-width:760px){.ot-page{padding:18px 14px}.ot-head h1{font-size:23px}.ot-detail-grid{grid-template-columns:1fr}.ot-order{grid-template-columns:1fr}.ot-order-side{text-align:left}.ot-hero{padding:18px}.ot-hero h2{font-size:19px}}@media(max-width:420px){.ot-meta{display:grid;gap:3px}.ot-meta span[aria-hidden]{display:none}.ot-hero-row{display:block}.ot-live{margin-top:15px}}
    `}</style>
    <div className="ot-shell">{orderId ? <OrderDetail {...tracking} navigate={navigate} /> : <OrderList {...tracking} />}</div>
  </main>;
}

function OrderList({ orders, loading, error, refresh }) {
  return <><header className="ot-head"><div><div className="ot-kicker">Rescue activity</div><h1>Order tracking</h1><p>Follow every donation and claimed-food delivery from one place.</p></div><button className="ot-icon-btn" onClick={refresh} aria-label="Refresh orders"><HiOutlineArrowPath /></button></header>{error && <div className="ot-alert">{error}</div>}{loading ? <div className="ot-empty">Loading your rescue orders…</div> : orders.length ? <div className="ot-list">{orders.map((order) => <Link className="ot-order" to={`/dashboard/orders/${order.$id}`} key={order.$id}><div className="ot-order-top"><span className="ot-food-icon"><HiOutlineShoppingBag /></span><div><h2>{order.name}</h2><div className="ot-meta"><span>{order.quantity} meals</span><span aria-hidden>•</span><span>{order.pickupLocation}</span><span aria-hidden>•</span><span>{new Date(order.$createdAt).toLocaleDateString()}</span></div></div></div><div className="ot-order-side"><span className="ot-status">{statusCopy[order.workflowStatus][0]}</span><small>View tracking →</small></div></Link>)}</div> : <div className="ot-empty">No rescue orders yet. Claimed food and your posted donations will appear here.</div>}</>;
}

function OrderDetail({ order, loading, error, busy, cancel, eta, progressPct, STATUS_STEPS, navigate }) {
  if (loading) return <div className="ot-empty">Loading rescue status…</div>;
  if (error && !order) return <><button className="ot-icon-btn" onClick={() => navigate(-1)}><HiOutlineArrowLeft /></button><div className="ot-alert" style={{ marginTop: 14 }}>{error}</div></>;
  if (!order) return <div className="ot-empty">This rescue could not be found.</div>;
  const [title, subtitle] = statusCopy[order.workflowStatus];
  return <><header className="ot-head"><div style={{ display: "flex", gap: 12 }}><button className="ot-icon-btn" onClick={() => navigate(-1)} aria-label="Back"><HiOutlineArrowLeft /></button><div><div className="ot-kicker">Order {order.$id.slice(0, 8)}</div><h1>Rescue details</h1></div></div></header>{error && <div className="ot-alert" style={{ marginBottom: 14 }}>{error}</div>}<div className="ot-detail-grid"><section><div className="ot-card ot-hero"><div className="ot-hero-row"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="ot-live"><i /> LIVE DATA</span></div><div className="ot-progress"><span style={{ width: `${progressPct}%` }} /></div><div className="ot-progress-copy"><span>{progressPct}% complete</span><span>{eta !== null ? `${eta} min remaining in rescue window` : order.workflowStatus === "completed" ? "Completed" : "No deadline"}</span></div></div><div className="ot-card"><p className="ot-label">Rescue progress</p><div className="ot-steps">{STATUS_STEPS.map((step, index) => { const active = index === order.currentStep && order.workflowStatus !== "cancelled"; const done = index < order.currentStep || order.workflowStatus === "completed"; return <div className={`ot-step ${done ? "done" : active ? "active" : ""}`} key={step.id}><span className="ot-step-icon">{done ? <HiOutlineCheckCircle /> : active ? <HiOutlineClock /> : <HiOutlineShoppingBag />}</span><div><h3>{step.label}</h3><p>{step.sub}</p></div></div>; })}</div></div></section><aside className="ot-side"><div className="ot-card"><p className="ot-label">Pickup from donor</p><div className="ot-address"><HiOutlineMapPin /><span>{order.pickupLocation}</span></div></div><div className="ot-card"><p className="ot-label">Deliver to receiver</p><div className="ot-address"><HiOutlineMapPin /><span>{order.deliveryAddress}</span></div></div><div className="ot-card"><p className="ot-label">Order summary</p><strong>{order.name}</strong><p style={{ margin: "5px 0 0", color: "var(--ot-muted)", fontSize: 12 }}>{order.quantity} meals · {order.description}</p></div><div className="ot-actions">{order.dropOffLocation && order.workflowStatus !== "cancelled" && <button className="ot-button primary" onClick={() => navigate("/dashboard/map")}><HiOutlineMap style={{ verticalAlign: "middle", marginRight: 6 }} />View donor-to-receiver route</button>}{order.workflowStatus === "posted" && <Link className="ot-button" to="/donations">View public listing</Link>}{["posted","reserved"].includes(order.workflowStatus) && <button className="ot-button danger" disabled={busy} onClick={cancel}><HiOutlineXCircle style={{ verticalAlign: "middle", marginRight: 6 }} />{busy ? "Cancelling…" : "Cancel rescue"}</button>}</div></aside></div></>;
}
